name: CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: Platform-System/CI-CD/.github/workflows/build-dotnet.yml@main
    secrets: inherit
    with:
      project_path: 'SystemContext.csproj'
      test_path: 'SystemContext.Tests/SystemContext.Tests.csproj'
      dependencies: 'Platform-System/BuildingBlocks'





